// Hand-written Russian names for SRD entities. The 5e-database ships a partial
// ru/ locale (conditions, skills, abilities, damage types, alignments...), but
// monsters, spells, classes, races and equipment are English-only there. The AI
// DM narrates in Russian, so it needs these to name things consistently instead
// of inventing a new translation every session.
//
// Keys are SRD indexes. Anything missing simply falls back to the English name.

export const classes = {
  barbarian: 'Варвар',
  bard: 'Бард',
  cleric: 'Жрец',
  druid: 'Друид',
  fighter: 'Воин',
  monk: 'Монах',
  paladin: 'Паладин',
  ranger: 'Следопыт',
  rogue: 'Плут',
  sorcerer: 'Чародей',
  warlock: 'Колдун',
  wizard: 'Волшебник',
};

export const races = {
  dragonborn: 'Драконорождённый',
  dwarf: 'Дварф',
  elf: 'Эльф',
  gnome: 'Гном',
  'half-elf': 'Полуэльф',
  'half-orc': 'Полуорк',
  halfling: 'Полурослик',
  human: 'Человек',
  tiefling: 'Тифлинг',
};

export const subraces = {
  'hill-dwarf': 'Холмовой дварф',
  'high-elf': 'Высший эльф',
  'rock-gnome': 'Скальный гном',
  lightfoot: 'Легконогий полурослик',
};

export const backgrounds = {
  acolyte: 'Прислужник',
};

export const schools = {
  abjuration: 'Ограждение',
  conjuration: 'Вызов',
  divination: 'Прорицание',
  enchantment: 'Очарование',
  evocation: 'Воплощение',
  illusion: 'Иллюзия',
  necromancy: 'Некромантия',
  transmutation: 'Преобразование',
};

export const equipment = {
  club: 'Дубинка',
  dagger: 'Кинжал',
  greatclub: 'Большая дубина',
  handaxe: 'Ручной топор',
  javelin: 'Метательное копьё',
  'light-hammer': 'Лёгкий молот',
  mace: 'Булава',
  quarterstaff: 'Боевой посох',
  sickle: 'Серп',
  spear: 'Копьё',
  'crossbow-light': 'Лёгкий арбалет',
  dart: 'Дротик',
  shortbow: 'Короткий лук',
  sling: 'Праща',
  battleaxe: 'Секира',
  flail: 'Цеп',
  glaive: 'Глефа',
  greataxe: 'Большой топор',
  greatsword: 'Двуручный меч',
  halberd: 'Алебарда',
  lance: 'Кавалерийское копьё',
  longsword: 'Длинный меч',
  maul: 'Молот',
  morningstar: 'Моргенштерн',
  pike: 'Пика',
  rapier: 'Рапира',
  scimitar: 'Скимитар',
  shortsword: 'Короткий меч',
  trident: 'Трезубец',
  'war-pick': 'Боевая кирка',
  warhammer: 'Боевой молот',
  whip: 'Кнут',
  blowgun: 'Духовая трубка',
  'crossbow-hand': 'Ручной арбалет',
  'crossbow-heavy': 'Тяжёлый арбалет',
  longbow: 'Длинный лук',
  net: 'Сеть',
  'padded-armor': 'Стёганый доспех',
  'leather-armor': 'Кожаный доспех',
  'studded-leather-armor': 'Проклёпанный кожаный доспех',
  'hide-armor': 'Шкурный доспех',
  'chain-shirt': 'Кольчужная рубаха',
  'scale-mail': 'Чешуйчатый доспех',
  breastplate: 'Кираса',
  'half-plate-armor': 'Полулаты',
  'ring-mail': 'Колечный доспех',
  'chain-mail': 'Кольчуга',
  splint: 'Наборный доспех',
  'plate-armor': 'Латы',
  shield: 'Щит',
  backpack: 'Рюкзак',
  bedroll: 'Спальник',
  rations: 'Рационы',
  'rope-hempen-50-feet': 'Пеньковая верёвка (50 фт.)',
  'rope-silk-50-feet': 'Шёлковая верёвка (50 фт.)',
  torch: 'Факел',
  'rations-1-day': 'Рационы (1 день)',
  'lantern-hooded': 'Закрытый фонарь',
  'lantern-bullseye': 'Направленный фонарь',
  lantern: 'Фонарь',
  'thieves-tools': 'Воровские инструменты',
  'healers-kit': 'Набор лекаря',
  'potion-of-healing': 'Зелье лечения',
  'holy-water-flask': 'Флакон святой воды',
  'crowbar': 'Лом',
  'hammer': 'Молоток',
  'piton': 'Пиктон',
  'tinderbox': 'Трутница',
  'waterskin': 'Бурдюк',
  'grappling-hook': 'Крюк-кошка',
  arrow: 'Стрелы',
  'crossbow-bolt': 'Арбалетные болты',
  'blowgun-needle': 'Иглы для духовой трубки',
  'sling-bullet': 'Пули для пращи',
  'component-pouch': 'Мешочек с компонентами',
  amulet: 'Амулет',
  emblem: 'Эмблема',
  reliquary: 'Реликварий',
  crystal: 'Кристалл',
  orb: 'Сфера',
  rod: 'Жезл',
  staff: 'Посох',
  wand: 'Волшебная палочка',
  totem: 'Тотем',
  'wooden-staff': 'Деревянный посох',
  'yew-wand': 'Тисовая палочка',
  'sprig-of-mistletoe': 'Веточка омелы',
  'explorers-pack': 'Набор путешественника',
  'dungeoneers-pack': 'Набор исследователя подземелий',
  'burglars-pack': 'Набор взломщика',
  'scholars-pack': 'Набор учёного',
  'priests-pack': 'Набор священника',
  'entertainers-pack': 'Набор артиста',
  'diplomats-pack': 'Набор дипломата',
  lute: 'Лютня',
  flute: 'Флейта',
  'pan-flute': 'Пан-флейта',
  drum: 'Барабан',
  horn: 'Рожок',
  'clothes-common': 'Простая одежда',
  'clothes-travelers': 'Дорожная одежда',
  'clothes-fine': 'Дорогая одежда',
  pouch: 'Поясная сумка',
  'oil-flask': 'Флакон масла',
  'candle': 'Свеча',
  'chalk': 'Мел',
  'ink-1-ounce-bottle': 'Чернила',
  'ink-pen': 'Перо',
  'paper-one-sheet': 'Бумага',
  'parchment-one-sheet': 'Пергамент',
  'blanket': 'Одеяло',
  'mess-kit': 'Котелок',
  'shovel': 'Лопата',
  'lock': 'Замок',
  'manacles': 'Кандалы',
  'caltrops': 'Чеснок',
  'ball-bearings': 'Металлические шарики',
  'hunting-trap': 'Охотничий капкан',
  'poison-basic': 'Яд (простой)',
  'antitoxin': 'Противоядие',
  'spellbook': 'Книга заклинаний',
};

export const monsters = {
  aboleth: 'Аболет',
  'adult-black-dragon': 'Взрослый чёрный дракон',
  'adult-blue-dragon': 'Взрослый синий дракон',
  'adult-brass-dragon': 'Взрослый латунный дракон',
  'adult-bronze-dragon': 'Взрослый бронзовый дракон',
  'adult-copper-dragon': 'Взрослый медный дракон',
  'adult-gold-dragon': 'Взрослый золотой дракон',
  'adult-green-dragon': 'Взрослый зелёный дракон',
  'adult-red-dragon': 'Взрослый красный дракон',
  'adult-silver-dragon': 'Взрослый серебряный дракон',
  'adult-white-dragon': 'Взрослый белый дракон',
  'air-elemental': 'Воздушный элементаль',
  ankheg: 'Анкег',
  ape: 'Обезьяна',
  'awakened-shrub': 'Пробуждённый куст',
  'awakened-tree': 'Пробуждённое дерево',
  axe_beak: 'Топороклюв',
  'axe-beak': 'Топороклюв',
  baboon: 'Бабуин',
  badger: 'Барсук',
  balor: 'Балор',
  bandit: 'Бандит',
  'bandit-captain': 'Главарь бандитов',
  banshee: 'Банши',
  basilisk: 'Василиск',
  bat: 'Летучая мышь',
  bear: 'Медведь',
  behir: 'Бехир',
  berserker: 'Берсерк',
  'black-bear': 'Чёрный медведь',
  'black-dragon-wyrmling': 'Чёрный дракончик',
  'black-pudding': 'Чёрная слизь',
  'blink-dog': 'Мерцающий пёс',
  'blood-hawk': 'Кровавый ястреб',
  'blue-dragon-wyrmling': 'Синий дракончик',
  boar: 'Кабан',
  'brown-bear': 'Бурый медведь',
  bugbear: 'Багбир',
  bulette: 'Булетта',
  camel: 'Верблюд',
  'cat': 'Кошка',
  centaur: 'Кентавр',
  chimera: 'Химера',
  chuul: 'Чуул',
  'clay-golem': 'Глиняный голем',
  cloaker: 'Клокер',
  'cloud-giant': 'Облачный великан',
  cockatrice: 'Кокатрикс',
  commoner: 'Простолюдин',
  constrictor_snake: 'Удав',
  'constrictor-snake': 'Удав',
  couatl: 'Коуатль',
  crab: 'Краб',
  crocodile: 'Крокодил',
  cultist: 'Культист',
  'cult-fanatic': 'Фанатик культа',
  'darkmantle': 'Тёмная мантия',
  deer: 'Олень',
  'death-dog': 'Пёс смерти',
  'deep-gnome-svirfneblin': 'Свирфнеблин',
  'dire-wolf': 'Лютый волк',
  djinni: 'Джинн',
  doppelganger: 'Доппельгангер',
  draft_horse: 'Тягловая лошадь',
  'draft-horse': 'Тягловая лошадь',
  dretch: 'Дретч',
  drider: 'Дриджер',
  druid: 'Друид (NPC)',
  dryad: 'Дриада',
  duergar: 'Дуэргар',
  eagle: 'Орёл',
  'earth-elemental': 'Земляной элементаль',
  'efreeti': 'Ифрит',
  elephant: 'Слон',
  elk: 'Лось',
  'ettercap': 'Эттеркап',
  ettin: 'Эттин',
  'fire-elemental': 'Огненный элементаль',
  'fire-giant': 'Огненный великан',
  'flesh-golem': 'Плотяной голем',
  'flying-snake': 'Летучая змея',
  'flying-sword': 'Летающий меч',
  'frost-giant': 'Ледяной великан',
  gargoyle: 'Горгулья',
  'gelatinous-cube': 'Желатиновый куб',
  ghast: 'Гхаст',
  ghost: 'Призрак',
  ghoul: 'Упырь',
  'giant-ape': 'Гигантская обезьяна',
  'giant-badger': 'Гигантский барсук',
  'giant-bat': 'Гигантская летучая мышь',
  'giant-boar': 'Гигантский кабан',
  'giant-centipede': 'Гигантская многоножка',
  'giant-crab': 'Гигантский краб',
  'giant-crocodile': 'Гигантский крокодил',
  'giant-eagle': 'Гигантский орёл',
  'giant-elk': 'Гигантский лось',
  'giant-fire-beetle': 'Гигантский огненный жук',
  'giant-frog': 'Гигантская лягушка',
  'giant-goat': 'Гигантский козёл',
  'giant-hyena': 'Гигантская гиена',
  'giant-lizard': 'Гигантская ящерица',
  'giant-octopus': 'Гигантский осьминог',
  'giant-owl': 'Гигантская сова',
  'giant-poisonous-snake': 'Гигантская ядовитая змея',
  'giant-rat': 'Гигантская крыса',
  'giant-scorpion': 'Гигантский скорпион',
  'giant-shark': 'Гигантская акула',
  'giant-spider': 'Гигантский паук',
  'giant-toad': 'Гигантская жаба',
  'giant-wasp': 'Гигантская оса',
  'giant-wolf-spider': 'Гигантский паук-волк',
  gibbering_mouther: 'Бормочущий рот',
  'gibbering-mouther': 'Бормочущий рот',
  gladiator: 'Гладиатор',
  gnoll: 'Гнолл',
  goat: 'Козёл',
  goblin: 'Гоблин',
  'gold-dragon-wyrmling': 'Золотой дракончик',
  gorgon: 'Горгона',
  'gray-ooze': 'Серая слизь',
  'green-dragon-wyrmling': 'Зелёный дракончик',
  'green-hag': 'Зелёная карга',
  grick: 'Грик',
  griffon: 'Грифон',
  grimlock: 'Гримлок',
  guard: 'Стражник',
  harpy: 'Гарпия',
  hawk: 'Ястреб',
  'hell-hound': 'Адская гончая',
  'hill-giant': 'Холмовой великан',
  hippogriff: 'Гиппогриф',
  hobgoblin: 'Хобгоблин',
  'homunculus': 'Гомункул',
  'horned-devil': 'Рогатый дьявол',
  hunter_shark: 'Акула-охотник',
  'hunter-shark': 'Акула-охотник',
  hydra: 'Гидра',
  hyena: 'Гиена',
  'ice-devil': 'Ледяной дьявол',
  imp: 'Бес',
  incubus: 'Инкуб',
  invisible_stalker: 'Невидимый охотник',
  'invisible-stalker': 'Невидимый охотник',
  'iron-golem': 'Железный голем',
  jackal: 'Шакал',
  'killer-whale': 'Косатка',
  knight: 'Рыцарь',
  kobold: 'Кобольд',
  kraken: 'Кракен',
  lamia: 'Ламия',
  lemure: 'Лемур',
  lich: 'Лич',
  lion: 'Лев',
  lizard: 'Ящерица',
  lizardfolk: 'Ящеролюд',
  mage: 'Маг',
  magmin: 'Магмин',
  mammoth: 'Мамонт',
  manticore: 'Мантикора',
  mastiff: 'Мастиф',
  medusa: 'Медуза',
  merfolk: 'Мерфолк',
  merrow: 'Мерроу',
  mimic: 'Мимик',
  minotaur: 'Минотавр',
  'minotaur-skeleton': 'Скелет минотавра',
  mule: 'Мул',
  mummy: 'Мумия',
  'mummy-lord': 'Владыка мумий',
  naga: 'Нага',
  'night-hag': 'Ночная карга',
  nightmare: 'Кошмар',
  noble: 'Дворянин',
  ochre_jelly: 'Охряное желе',
  'ochre-jelly': 'Охряное желе',
  octopus: 'Осьминог',
  ogre: 'Огр',
  'ogre-zombie': 'Огр-зомби',
  oni: 'Они',
  orc: 'Орк',
  otyugh: 'Отиг',
  owl: 'Сова',
  owlbear: 'Совомедведь',
  panther: 'Пантера',
  pegasus: 'Пегас',
  'phase-spider': 'Фазовый паук',
  pixie: 'Пикси',
  planetar: 'Планетар',
  plesiosaurus: 'Плезиозавр',
  poisonous_snake: 'Ядовитая змея',
  'poisonous-snake': 'Ядовитая змея',
  polar_bear: 'Белый медведь',
  'polar-bear': 'Белый медведь',
  pony: 'Пони',
  priest: 'Жрец (NPC)',
  pseudodragon: 'Псевдодракон',
  'purple-worm': 'Пурпурный червь',
  quasit: 'Квазит',
  quipper: 'Квиппер',
  rakshasa: 'Ракшас',
  rat: 'Крыса',
  raven: 'Ворон',
  'red-dragon-wyrmling': 'Красный дракончик',
  'reef-shark': 'Рифовая акула',
  remorhaz: 'Реморхаз',
  rhinoceros: 'Носорог',
  'riding-horse': 'Верховая лошадь',
  'roc': 'Рух',
  'roper': 'Роупер',
  'rug-of-smothering': 'Удушающий ковёр',
  'rust-monster': 'Ржавый монстр',
  saber_toothed_tiger: 'Саблезубый тигр',
  'saber-toothed-tiger': 'Саблезубый тигр',
  sahuagin: 'Сахуагин',
  salamander: 'Саламандра',
  satyr: 'Сатир',
  scorpion: 'Скорпион',
  scout: 'Разведчик',
  'sea-hag': 'Морская карга',
  'sea-horse': 'Морской конёк',
  shadow: 'Тень',
  shambling_mound: 'Бродячая насыпь',
  'shambling-mound': 'Бродячая насыпь',
  shrieker: 'Крикун',
  'silver-dragon-wyrmling': 'Серебряный дракончик',
  skeleton: 'Скелет',
  spectator: 'Спектатор',
  specter: 'Спектр',
  spider: 'Паук',
  spy: 'Шпион',
  sprite: 'Спрайт',
  'steam-mephit': 'Паровой мефит',
  'stirge': 'Стирж',
  'stone-giant': 'Каменный великан',
  'stone-golem': 'Каменный голем',
  'storm-giant': 'Штормовой великан',
  succubus: 'Суккуб',
  swarm_of_bats: 'Рой летучих мышей',
  'swarm-of-bats': 'Рой летучих мышей',
  'swarm-of-insects': 'Рой насекомых',
  'swarm-of-poisonous-snakes': 'Рой ядовитых змей',
  'swarm-of-quippers': 'Рой квипперов',
  'swarm-of-rats': 'Рой крыс',
  'swarm-of-ravens': 'Рой воронов',
  tarrasque: 'Тарраск',
  thug: 'Головорез',
  tiger: 'Тигр',
  treant: 'Древень',
  triceratops: 'Трицератопс',
  troll: 'Тролль',
  'tribal-warrior': 'Племенной воин',
  twig_blight: 'Ветвичная порча',
  tyrannosaurus_rex: 'Тираннозавр',
  'tyrannosaurus-rex': 'Тираннозавр',
  unicorn: 'Единорог',
  vampire: 'Вампир',
  'vampire-spawn': 'Вампирское отродье',
  veteran: 'Ветеран',
  'violet-fungus': 'Фиолетовый грибок',
  vulture: 'Гриф',
  warhorse: 'Боевой конь',
  'warhorse-skeleton': 'Скелет боевого коня',
  'water-elemental': 'Водяной элементаль',
  weasel: 'Ласка',
  werebear: 'Медведь-оборотень',
  wereboar: 'Кабан-оборотень',
  wererat: 'Крысолюд-оборотень',
  weretiger: 'Тигр-оборотень',
  werewolf: 'Вервольф',
  'white-dragon-wyrmling': 'Белый дракончик',
  'wight': 'Умертвие',
  'will-o-wisp': 'Блуждающий огонёк',
  winter_wolf: 'Зимний волк',
  'winter-wolf': 'Зимний волк',
  wolf: 'Волк',
  worg: 'Ворг',
  wraith: 'Мгла',
  wyvern: 'Виверна',
  xorn: 'Ксорн',
  'young-black-dragon': 'Молодой чёрный дракон',
  'young-blue-dragon': 'Молодой синий дракон',
  'young-green-dragon': 'Молодой зелёный дракон',
  'young-red-dragon': 'Молодой красный дракон',
  'young-white-dragon': 'Молодой белый дракон',
  zombie: 'Зомби',
};

// Only the spells a level 1-5 party actually reaches for. The rest keep their
// English names; the DM translates them inline when it matters.
export const spells = {
  'acid-splash': 'Кислотные брызги',
  'aid': 'Помощь',
  'alarm': 'Сигнализация',
  'animal-friendship': 'Дружба с животными',
  'bane': 'Проклятие',
  'barkskin': 'Кора',
  'bless': 'Благословение',
  'blindness-deafness': 'Слепота/глухота',
  'blur': 'Размытый образ',
  'burning-hands': 'Огненные ладони',
  'call-lightning': 'Вызов молнии',
  'charm-person': 'Очарование личности',
  'chill-touch': 'Ледяное прикосновение',
  'command': 'Приказ',
  'comprehend-languages': 'Понимание языков',
  'counterspell': 'Контрзаклинание',
  'cure-wounds': 'Лечение ран',
  'dancing-lights': 'Пляшущие огоньки',
  'darkness': 'Тьма',
  'darkvision': 'Тёмное зрение',
  'detect-magic': 'Обнаружение магии',
  'dispel-magic': 'Рассеивание магии',
  'druidcraft': 'Друидизм',
  'eldritch-blast': 'Мистический заряд',
  'entangle': 'Опутывающие растения',
  'faerie-fire': 'Огонь фей',
  'false-life': 'Псевдожизнь',
  'fear': 'Страх',
  'feather-fall': 'Падение пёрышком',
  'find-familiar': 'Поиск фамильяра',
  'fire-bolt': 'Огненный снаряд',
  'fireball': 'Огненный шар',
  'fly': 'Полёт',
  'fog-cloud': 'Туманное облако',
  'grease': 'Жир',
  'guidance': 'Указание',
  'guiding-bolt': 'Указующий снаряд',
  'haste': 'Ускорение',
  'healing-word': 'Лечащее слово',
  'hellish-rebuke': 'Адское возмездие',
  'heroism': 'Героизм',
  'hold-person': 'Удержание личности',
  'hunters-mark': 'Метка охотника',
  'identify': 'Опознание',
  'invisibility': 'Невидимость',
  'jump': 'Прыжок',
  'knock': 'Открывание',
  'lesser-restoration': 'Малое восстановление',
  'levitate': 'Левитация',
  'light': 'Свет',
  'lightning-bolt': 'Молния',
  'longstrider': 'Шаг',
  'mage-armor': 'Доспехи мага',
  'mage-hand': 'Волшебная рука',
  'magic-missile': 'Волшебная стрела',
  'mending': 'Починка',
  'message': 'Послание',
  'minor-illusion': 'Малая иллюзия',
  'mirror-image': 'Отражения',
  'misty-step': 'Туманный шаг',
  'pass-without-trace': 'Незримый путь',
  'poison-spray': 'Ядовитые брызги',
  'prayer-of-healing': 'Молитва лечения',
  'prestidigitation': 'Фокусы',
  'produce-flame': 'Сотворение пламени',
  'protection-from-evil-and-good': 'Защита от зла и добра',
  'ray-of-frost': 'Луч холода',
  'revivify': 'Оживление',
  'sacred-flame': 'Священное пламя',
  'sanctuary': 'Убежище',
  'scorching-ray': 'Палящий луч',
  'shatter': 'Звуковой удар',
  'shield': 'Щит',
  'shield-of-faith': 'Щит веры',
  'shocking-grasp': 'Шокирующее прикосновение',
  'silence': 'Тишина',
  'sleep': 'Сон',
  'spare-the-dying': 'Уход за умирающим',
  'speak-with-animals': 'Разговор с животными',
  'spider-climb': 'Паучье лазанье',
  'spike-growth': 'Шипы',
  'spiritual-weapon': 'Духовное оружие',
  'stinking-cloud': 'Зловонное облако',
  'suggestion': 'Внушение',
  'thaumaturgy': 'Чудотворство',
  'thunderwave': 'Волна грома',
  'true-strike': 'Верный удар',
  'unseen-servant': 'Невидимый слуга',
  'vicious-mockery': 'Злая насмешка',
  'web': 'Паутина',
  'witch-bolt': 'Ведьмин снаряд',
};

export const magicItems = {
  'potion-of-healing': 'Зелье лечения',
  'bag-of-holding': 'Сумка хранения',
  'cloak-of-elvenkind': 'Плащ эльфийского вида',
  'boots-of-elvenkind': 'Сапоги эльфийского вида',
  'ring-of-protection': 'Кольцо защиты',
  'wand-of-magic-missiles': 'Жезл волшебных стрел',
  'bracers-of-defense': 'Наручи защиты',
  'gauntlets-of-ogre-power': 'Перчатки огрской силы',
  'boots-of-striding-and-springing': 'Сапоги ходьбы и прыжков',
  'immovable-rod': 'Незыблемый стержень',
};

export const creatureTypes = {
  aberration: 'аберрация',
  beast: 'зверь',
  celestial: 'небожитель',
  construct: 'конструкт',
  dragon: 'дракон',
  elemental: 'элементаль',
  fey: 'фея',
  fiend: 'исчадие',
  giant: 'великан',
  humanoid: 'гуманоид',
  monstrosity: 'монстр',
  ooze: 'слизь',
  plant: 'растение',
  undead: 'нежить',
  swarm: 'рой',
};

export const sizes = {
  Tiny: 'Крошечный',
  Small: 'Маленький',
  Medium: 'Средний',
  Large: 'Большой',
  Huge: 'Огромный',
  Gargantuan: 'Громадный',
};
